config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get "about" => 'pages#about'

  get "product" => 'pages#products'

  get "contact" => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def products
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
    <div class="preloader">
      <img src="img/preloader.gif" alt="Loading..." class="preloader__img">
    </div>


    <!-- STATIC TOPBAR
    ============================== -->
    <div class="topbar hidden-xs hidden-sm">
      <div class="container">
        <!-- Social links -->
        <ul class="topbar-nav topbar-nav_left">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-vk"></i></a></li>
          <li><a href="#"><i class="fa fa-stumbleupon"></i></a></li>
        </ul>
        <ul class="topbar-nav topbar-nav_right">

          <!-- Account links -->
          <li><a href="sign-in.html">Sign In</a></li>
          <li><a href="sing-up.html">Sign Up</a></li>
        </ul>
      </div> <!-- / .container -->
    </div> <!-- / .topbar -->
    <div class="navbar__hr hidden-xs hidden-sm"></div>






    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- Toggle button -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Brand name -->
          <%= link_to '10X Pickup', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <!-- Navbar links -->
          <ul class="nav navbar-nav navbar-right">

            <!-- Home -->
            <li class="dropdown">
              <%= link_to 'Home', root_path %>
            </li>

            <!-- Profile -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Profile <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="sign-in.html">Sign In: Default</a></li>
                    <li><a href="sign-in_option-1.html">Sign In: Option 1</a></li>
                  </ul>
                </li>
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="sign-up.html">Sign Up: Default</a></li>
                    <li><a href="sign-up_option-1.html">Sign Up: Option 1</a></li>
                  </ul>
                </li>
                <li><a href="profile.html">User Profile</a></li>
              </ul>
            </li>

            <!-- Portfolio -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Portfolio <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'About', about_path %></li>
                <li><a href="portfolio-item.html">Portfolio Item</a></li>
              </ul>
            </li>

            <!-- Blog -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Blog <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="blog.html">Blog</a></li>
                <li><a href="blog-post.html">Blog Post</a></li>
              </ul>
            </li>

            <!-- Shop -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Shop <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Products', product_path %></li>
                <li><a href="shop-item.html">Shop Item</a></li>
                <li><a href="shopping-cart.html">Shopping Cart</a></li>
              </ul>
            </li>

            <!-- More pages -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                More Pages <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="about-us.html">About Us</a></li>
                <li><a href="coming-soon.html">Coming Soon</a></li>
                <li><%= link_to 'Contact us', contact_path %></li>
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help Center</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="help-center.html">Help Center</a></li>
                    <li><a href="help-item.html">Help Item</a></li>
                  </ul>
                </li>
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pricing Options</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="pricing_boxes.html">Pricing Options: Boxes</a></li>
                    <li><a href="pricing_table.html">Pricing Options: Table</a></li>
                  </ul>
                </li> 
                <li><a href="services.html">Services</a></li>
                <li><a href="search-results.html">Search Results</a></li>
                <li><a href="timeline.html">Timeline</a></li>
                <li><a href="error-page.html">404 Error</a></li>               
              </ul>


        </div> <!-- / .navbar-collapse -->
      </div> <!-- / .container -->
    </div> <!-- / .navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tenex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="body_index">



<%= render 'layouts/topbar' %>
<%= render 'layouts/header' %>
<%= render 'layouts/heroblock' %>



<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
    <!-- HERO BLOCK
    ============================== -->
    <div class="hero hero__bs">
      <div class="hero__inner">
        <div class="wrapper">
          <div class="wrapper__inner">
            <div class="container">
              <div class="row" id="hero__content">
                <div class="col-sm-12 text-center">
                  <h1 class="hero__h1">Create Beautiful Websites</h1>
                  <h2 class="hero__h2">Easily With Beatrix</h2>
                  <p class="hero__intro">
                    Multipurpose responsive template powered by Bootstrap
                  </p>
                  <div class="hero__action">
                    <a href="#" class="btn btn-lg btn-primary">Purchase now</a>
                  </div>
                </div>
              </div> <!-- / .row -->
            </div> <!-- / .container -->
          </div> <!-- / .wrapper__inner -->
        </div> <!-- / .wrapper -->
      </div> <!-- / .hero__inner -->

      <!-- Backstretch controls -->
      <div class="hero__ctrl js-hero-bs__ctrl">
        <a href="#hero__carousel" role="button" data-slide="prev">
          <i class="fa fa-step-backward"></i>
        </a>
        <a href="#" data-slide="pause" class="visible-inline-block playback">
          <i class="fa fa-pause"></i>
        </a>
        <a href="#" data-slide="resume" class="playback hidden">
          <i class="fa fa-play"></i>
        </a>
        <a href="#hero__carousel" role="button" data-slide="next">
          <i class="fa fa-step-forward"></i>
        </a>
      </div> <!-- / .hero__ctrl -->
    </div> <!-- / .hero -->


    <!-- KEY FEATURES
    ============================== -->
    <div class="section section_features">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1 class="section__title">
              Our Core Features
            </h1>
            <p class="section__intro">
              Beatrix is a super flexible HTML5 template that would perfectly fit a project of any size and complexity
            </p>
            <div class="section__hr section__hr_center"></div>
          </div>
        </div> <!-- / .row -->
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <!-- Features item #1 -->
            <div class="features__item">
              <!-- Icon -->
              <div class="features__icon wow flipInY">
                <i class="fa fa-check"></i>
                <i class="fa fa-check"></i> <!-- Required for animation -->
              </div>
              <!-- Title -->
              <h2 class="features__title">
                Truly Responsive
              </h2>
              <!-- Intro -->
              <p class="features__intro">
                Looks equally great on your laptop, tablet, and phone. Try to resize your window to see what we mean.
              </p>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <!-- Features item #2 -->
            <div class="features__item">
              <!-- Icon -->
              <div class="features__icon wow flipInY" data-wow-delay=".2s">
                <i class="fa fa-birthday-cake"></i>
                <i class="fa fa-birthday-cake"></i> <!-- Required for animation -->
              </div>
              <!-- Title -->
              <h2 class="features__title">
                Built with LESS
              </h2>
              <!-- Intro -->
              <p class="features__intro">
                Build on the source LESS code or quickly get started with precompiled CSS if you are a novice developer.
              </p>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <!-- Features item #3 -->
            <div class="features__item">
              <!-- Icon -->
              <div class="features__icon wow flipInY" data-wow-delay=".4s">
                <i class="fa fa-envelope"></i>
                <i class="fa fa-envelope"></i> <!-- Required for animation -->
              </div>
              <!-- Title -->
              <h2 class="features__title">
                PHP Contact Form
              </h2>
              <!-- Intro -->
              <p class="features__intro">
                Beatrix comes with a fully functional PHP contact form with built in spam protection powered by reCaptcha.
              </p>
            </div>
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </div> <!-- / .section -->

app/views/pages/products.html.erb
<h1>Pages#products</h1>
<p>Find me in app/views/pages/products.html.erb</p>